### ISSUE TITLE
Iframe doesnt work on underlying folders

### ISSUE THREAD

**Issue by Jelle-vz** [egoist/docute-iframe#7] opened 2017-08-15 10:29 UTC
I have the following setup:
"docute": "^3.4.8",
 "docute-iframe": "^0.3.1"

And a folder structure:
- Application root
-- components
--- component_name
----- readme.md 

In the readme file i try to run some Vuejs code. but the iframe won't load. I just get the normal '\<pre>' notation

It does work on de the readme.md on the root of the application.

**Comment by egoist** [comment] 2017-08-16 01:55
can you provide a repo that I can use to reproduce? it's hard to tell just by looking at the issue.

**Comment by Jelle-vz** [comment] 2017-08-16 06:21
Yes, sure, I've send you an invitation to the repo. 
Thanks in advance!

**Comment by Jelle-vz** [comment] 2017-08-22 07:05
@egoist Did you have time to check out the issue?

**Comment by egoist** [comment] 2017-08-22 08:59
Sorry for being late to respond, but seems it actually works for me?

![2017-08-22 4 58 24](https://user-images.githubusercontent.com/8784712/29557308-3e53d590-875b-11e7-9529-7c221d7b3ffc.png)

**Comment by Jelle-vz** [comment] 2017-09-01 07:22
Thats strange! I'm working on a windows machine :| maybe thats the problem?

**Comment by andrewmcc** [comment] 2017-11-10 09:54
I'm getting the same problem with the usage example in the documentation.  If the runnable code is in the main README.md file then it works on all platforms.  However, it doesn't work on Windows inside a new page (either top-level or subdirectory).

I've tested on two separate Windows 10 machines and both fail (beforeParse() never fires and the iframe isn't inserted).  The same code works as expected on Linux.

I'll try and look into it again tonight, but it's a difficult one to debug.

**Comment by andrewmcc** [comment] 2017-11-10 11:41
It just needed the regex modified for Windows - should be fixed by PR #8

**Closed as completed** 2017-11-10 13:38 UTC

**Comment by egoist** [comment] 2017-11-10 13:56
Hopefully it's fixed in latest version, thanks to @andrewmcc
